<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Authors>MrR013X404</Authors>
    <Description>A lightweight, fast, and open-source music player for Windows</Description>
    <PackageProjectUrl>https://github.com/MrR013X404/Qorith</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MrR013X404/Qorith</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
