<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <StartupObject>Qorith.UI.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Windows.Forms" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Qorith.Core/Qorith.Core.csproj" />
  </ItemGroup>

</Project>
